class CONFIG(object):

    SQLALCHEMY_DATABASE_URI = 'sqlite:///gietro.sqlite'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ECHO = True
    DEBUG = True


RESULTATS_PAR_PAGE = 10
AUTRES_RESULTATS= 50
